




.build/atmega328/src/powerline.cpp : src/powerline.ino
	@mkdir -p .build/atmega328/src
	@echo [93msrc/powerline.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/atmega328/src/powerline.cpp
	@true

